version: '3.8'
services:
  digitalnotes:
    container_name: digitalnotes
    build: ./src
    volumes:
      - ./src:/usr/src/app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:4.4.0-bionic
    container_name: mongodb
    environment:
      - HOST="0.0.0.0"
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=admin
    volumes:
    - ./mongodb/data:/data/db
    ports:
      - "27017:27017"